name: Update BDPM pipeline

on:
  schedule:
    - cron: "0 4 * * *"  # tous les jours 4h

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install deps
        run: npm install

      - name: Update submodule
        run: git submodule update --remote bdpm

      - name: Build BDPM index
        run: node scripts/build-bdpm.js

      - name: Commit updated index
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add data bdpm.db
          git commit -m "chore: update BDPM dataset" || echo "No changes"
          git push